name: Deploy to Vercel and Upload Source Maps to PostHog

on:
  push:
    branches:
      - main  # You can change this branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  # Adjust the version to your project's needs

    - name: Install dependencies
      run: npm install

    - name: Build the Next.js app
      run: npm run build

    - name: Install PostHog CLI
      run: |
        curl -fsSL https://github.com/PostHog/posthog/releases/download/posthog-cli-v0.0.4/posthog-cli-installer.sh -o posthog-cli-installer.sh
        sh posthog-cli-installer.sh
      
    - name: Inject and upload source maps to PostHog
      env:
        POSTHOG_CLI_ENV_ID: ${{ secrets.POSTHOG_CLI_ENV_ID }}
        POSTHOG_CLI_TOKEN: ${{ secrets.POSTHOG_CLI_TOKEN }}
      run: |
        posthog-cli sourcemap inject --directory ./.next
        posthog-cli sourcemap upload --directory ./.next 


    - name: Remove source maps from build directory
      run: |
        find ./.next -type f -name "*.map" -delete

    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v20
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }} # Optional, needed if you're using an organization
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        vercel-args: '--prod' # Use --prod flag for production deployment

    - name: Clean up Vercel CLI
      run: rm -rf vercel-cli.zip vercel